export const REQUEST_SEARCH = 'catalog/REQUEST_SEARCH';
export const REQUEST_SEARCH_COMPLETED = 'catalog/REQUEST_SEARCH_COMPLETED';
export const REQUEST_SEARCH_FAILED = 'catalog/REQUEST_SEARCH_FAILED';
